# Generated by Django 5.2.1 on 2026-09-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculosDeJuros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InicioPeriodo', models.DateField()),
                ('FimPeriodo', models.DateField()),
                ('CodigoSegmento', models.CharField(max_length=50)),
                ('Segmento', models.CharField(max_length=100)),
                ('CodigoModalidade', models.CharField(max_length=50)),
                ('Modalidade', models.CharField(max_length=100)),
                ('Posicao', models.CharField(max_length=50)),
                ('InstituicaoFinanceira', models.CharField(max_length=100)),
                ('CNPJ8', models.CharField(max_length=8)),
                ('TaxaJurosAoMes', models.DecimalField(decimal_places=4, max_digits=10)),
                ('TaxaJurosAoAno', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
